#!/usr/bin/env python3
"""Generate src/font5x7.inc.S, the font the camera-side menu draws with.

The camera's own text renderer draws one line into a rectangle the handler
hardcodes, which is no use for a menu of rows. Carrying our own font means the
payload can put a character anywhere in the OSD layer with nothing but byte
writes: no display lock, no firmware call, no present.

Glyphs are written here as art so they can be read and corrected. Each is five
columns of seven rows; the emitted byte per column has bit 0 as the top row.
Only the characters the menu actually uses are defined; anything else draws as
blank rather than as whatever happened to be next in the table.
"""
import pathlib

GLYPHS = {
    '0': ("01110", "10001", "10011", "10101", "11001", "10001", "01110"),
    '1': ("00100", "01100", "00100", "00100", "00100", "00100", "01110"),
    '2': ("01110", "10001", "00001", "00010", "00100", "01000", "11111"),
    '3': ("11111", "00010", "00100", "00010", "00001", "10001", "01110"),
    '4': ("00010", "00110", "01010", "10010", "11111", "00010", "00010"),
    '5': ("11111", "10000", "11110", "00001", "00001", "10001", "01110"),
    '6': ("00110", "01000", "10000", "11110", "10001", "10001", "01110"),
    '7': ("11111", "00001", "00010", "00100", "01000", "01000", "01000"),
    '8': ("01110", "10001", "10001", "01110", "10001", "10001", "01110"),
    '9': ("01110", "10001", "10001", "01111", "00001", "00010", "01100"),
    'A': ("01110", "10001", "10001", "11111", "10001", "10001", "10001"),
    'B': ("11110", "10001", "10001", "11110", "10001", "10001", "11110"),
    'C': ("01110", "10001", "10000", "10000", "10000", "10001", "01110"),
    'D': ("11100", "10010", "10001", "10001", "10001", "10010", "11100"),
    'E': ("11111", "10000", "10000", "11110", "10000", "10000", "11111"),
    'F': ("11111", "10000", "10000", "11110", "10000", "10000", "10000"),
    'G': ("01110", "10001", "10000", "10111", "10001", "10001", "01111"),
    'H': ("10001", "10001", "10001", "11111", "10001", "10001", "10001"),
    'I': ("01110", "00100", "00100", "00100", "00100", "00100", "01110"),
    'J': ("00111", "00010", "00010", "00010", "00010", "10010", "01100"),
    'K': ("10001", "10010", "10100", "11000", "10100", "10010", "10001"),
    'L': ("10000", "10000", "10000", "10000", "10000", "10000", "11111"),
    'M': ("10001", "11011", "10101", "10101", "10001", "10001", "10001"),
    'N': ("10001", "11001", "10101", "10011", "10001", "10001", "10001"),
    'O': ("01110", "10001", "10001", "10001", "10001", "10001", "01110"),
    'P': ("11110", "10001", "10001", "11110", "10000", "10000", "10000"),
    'Q': ("01110", "10001", "10001", "10001", "10101", "10010", "01101"),
    'R': ("11110", "10001", "10001", "11110", "10100", "10010", "10001"),
    'S': ("01111", "10000", "10000", "01110", "00001", "00001", "11110"),
    'T': ("11111", "00100", "00100", "00100", "00100", "00100", "00100"),
    'U': ("10001", "10001", "10001", "10001", "10001", "10001", "01110"),
    'V': ("10001", "10001", "10001", "10001", "10001", "01010", "00100"),
    'W': ("10001", "10001", "10001", "10101", "10101", "11011", "10001"),
    'X': ("10001", "10001", "01010", "00100", "01010", "10001", "10001"),
    'Y': ("10001", "10001", "01010", "00100", "00100", "00100", "00100"),
    'Z': ("11111", "00001", "00010", "00100", "01000", "10000", "11111"),
    ' ': ("00000",) * 7,
    '-': ("00000", "00000", "00000", "01110", "00000", "00000", "00000"),
    '.': ("00000", "00000", "00000", "00000", "00000", "01100", "01100"),
    ':': ("00000", "01100", "01100", "00000", "01100", "01100", "00000"),
    '>': ("01000", "00100", "00010", "00001", "00010", "00100", "01000"),
    '?': ("01110", "10001", "00010", "00100", "00100", "00000", "00100"),
}

# The payload indexes the table with (character - 0x20), so every code from
# space to 'Z' needs a slot even when it is blank.
FIRST, LAST = 0x20, ord('Z')


def columns(art):
    for x in range(5):
        value = 0
        for y in range(7):
            if art[y][x] == '1':
                value |= 1 << y
        yield value


def main():
    out = [
        '/* Generated by tools/make_font.py -- edit the art there, not here.',
        ' *',
        ' * Five columns per glyph, one byte each, bit 0 = top row. Indexed by',
        f' * (character - {FIRST:#x}); undefined characters are blank.',
        ' */',
        '.global font5x7',
        'font5x7:',
    ]
    blank = (0, 0, 0, 0, 0)
    for code in range(FIRST, LAST + 1):
        glyph = GLYPHS.get(chr(code))
        data = tuple(columns(glyph)) if glyph else blank
        name = chr(code) if glyph and chr(code) != ' ' else 'space' if code == 0x20 else '?'
        out.append('    .byte ' + ', '.join(f'0x{v:02X}' for v in data)
                   + f'    @ {name}')
    out.append('')
    out.append(f'.equ FONT_FIRST, {FIRST:#x}')
    out.append(f'.equ FONT_LAST,  {LAST:#x}')
    out.append('.equ FONT_W, 5')
    out.append('.equ FONT_H, 7')
    out.append('')
    target = pathlib.Path(__file__).resolve().parent.parent / 'src/font5x7.inc.S'
    target.write_text('\n'.join(out))
    print(f'{target}: {LAST - FIRST + 1} glyph slots')


if __name__ == '__main__':
    main()
